# Generated by Django 3.2.5 on 2021-07-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrionApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetos',
            name='ProjetoParticipantes',
        ),
    ]
