# Generated by Django 3.2.5 on 2021-07-02 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OrionApp', '0003_auto_20210701_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='ProjetoDataFinal',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projetos',
            name='ProjetoDataInicial',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projetos',
            name='ProjetoParticipantes',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projetos',
            name='ProjetoRisco',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projetos',
            name='ProjetoValor',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
